<?php

function ihg_connector_menu(){
	$items = array();
	$items['ihg/connector/sync'] = array(
			'page callback' => 'ihg_connector_sync',
			'access callback' => TRUE,
			'file' => 'ihg_connector.inc'
	);
	$items['ihg/connector/last_data.json'] = array(
		'page callback' => 'ihg_connector_last_data_json',
		'access callback' => TRUE,
		'file' => 'ihg_connector.inc'		
	);
	$items['ihg/connector/data.json'] = array(
		'page callback' => 'ihg_connector_data_json',
		'access callback' => TRUE,
		'file' => 'ihg_connector.inc'
	);
	$items['ihg/connector/images.json'] = array(
			'page callback' => 'ihg_connector_images_json',
			'access callback' => TRUE,
			'file' => 'ihg_connector.inc'
	);
	$items['ihg/data_version'] = array(
			'page callback' => 'ihg_connector_data_version',
			'access callback' => TRUE,
	);
	
	return $items;
}

function ihg_connector_cronapi($op, $job = NULL) {

	if ($op == 'list') {
		$items['ihg_connector_generate_data'] = array(
				'description' => 'Genera i dati json per la presentazione',
				'rule' => '/15 * * * *', // ogni 15 minuti
		);
		return $items;
	}
	elseif ($op == 'execute') {
		switch ($job) {
			case 'ihg_connector_generate_data':
				_ihg_connector_generate_data();
				break;
		}
	}

}

function _ihg_connector_generate_data(){
	include_once drupal_get_path('module', 'ihg_connector') . '/ihg_connector.inc';
	
	$data_dir = $base_path . "/data";

	// genera il file json
	$json_data = drupal_json_encode(_ihg_connector_last_data_json());
	$json_data = 'var ihg_data = ' . $json_data;
	if( FALSE === file_unmanaged_save_data($json_data, 'public://preview/data/data.json', FILE_EXISTS_REPLACE)){
		watchdog('cron', 'Non è stato possibile generare il file data.json',null, WATCHDOG_ERROR);
		return false;		
	}

	watchdog('cron', 'il file data.json è stato generato',null, WATCHDOG_INFO);
	return true;
	
}


function ihg_connector_node_update($node){
	$data_last_version = variable_get('data_last_version', 0);
	variable_set('data_last_version', ++$data_last_version);
}

function ihg_connector_data_version(){
	print variable_get('data_last_version', 0);
}
