<?php

function ihg_connector_menu(){
	$items = array();
	$items['ihg/connector/sync'] = array(
			'page callback' => 'ihg_connector_sync',
			'access callback' => TRUE,
			'file' => 'ihg_connector.inc'
	);
	$items['ihg/connector/last_data.json'] = array(
		'page callback' => 'ihg_connector_last_data_json',
		'access callback' => TRUE,
		'file' => 'ihg_connector.inc'		
	);
	$items['ihg/connector/data.json'] = array(
		'page callback' => 'ihg_connector_data_json',
		'access callback' => TRUE,
		'file' => 'ihg_connector.inc'
	);
	$items['ihg/connector/images.json'] = array(
			'page callback' => 'ihg_connector_images_json',
			'access callback' => TRUE,
			'file' => 'ihg_connector.inc'
	);
	$items['ihg/data_version'] = array(
			'page callback' => 'ihg_connector_data_version',
			'access callback' => TRUE,
	);
	
	return $items;
}

function ihg_connector_cronapi($op, $job = NULL) {

	if ($op == 'list') {
		$items['ihg_connector_generate_data'] = array(
				'description' => 'Genera i dati json per la presentazione',
				'rule' => '/15 * * * *', // ogni 15 minuti
		);
		return $items;
	}
	elseif ($op == 'execute') {
		switch ($job) {
			case 'ihg_connector_generate_data':
				_ihg_connector_generate_data();
				break;
		}
	}

}

function _ihg_connector_generate_data(){
	include_once drupal_get_path('module', 'ihg_connector') . '/ihg_connector.inc';
	$wrapper = file_stream_wrapper_get_instance_by_uri('public://');
	$file_realpath = $wrapper->realpath();
	$styles_realpath = $file_realpath . "/styles";
	$base_path = $file_realpath . "/preview";
	
	$data_dir = $base_path . "/data";

	
	// rimuove la cartella data
	$ret = exec('rm -rf ' . $data_dir, $output, $return_var);
	
	if( FALSE === $ret ){
		watchdog('cron', 'Non è stato possibile rimuovere la directory @dir',array('@dir' => $data_dir), WATCHDOG_ERROR);
		return false;
	}
	if( FALSE === mkdir($data_dir) ){
		watchdog('cron', 'Non è stato possibile creare la directory @dir',array('@dir' => $data_dir), WATCHDOG_ERROR);
		return false;
	}
	// genera il file json
	$json_data = drupal_json_encode(_ihg_connector_last_data_json());
	$json_data = 'var ihg_data = ' . $json_data;
	if( FALSE === file_unmanaged_save_data($json_data, 'public://preview/data/data.json', FILE_EXISTS_REPLACE)){
		watchdog('cron', 'Non è stato possibile generare il file data.json',null, WATCHDOG_ERROR);
		return false;		
	}
	// copia tutte le immagini
	$copy_cmd = 'cp -r ' . $styles_realpath . ' ' . $data_dir . '/';
	if( FALSE === system($copy_cmd) ){
		watchdog('cron', 'Non è stato possibile copiare le immagini in styles',null, WATCHDOG_ERROR);
		return false;
	}
	watchdog('cron', 'La presentazione è stata correttamente aggiornata',null, WATCHDOG_INFO);
	return true;
	
}


function ihg_connector_node_update($node){
	$data_last_version = variable_get('data_last_version', 0);
	variable_set('data_last_version', ++$data_last_version);
}

function ihg_connector_data_version(){
	print variable_get('data_last_version', 0);
}
